src/Desymfony/DesymfonyBundle/Entity/Ponente.php
<?php

namespace Desymfony\DesymfonyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Desymfony\DesymfonyBundle\Entity
 *
 * @ORM\Table(name="ponente")
 * @ORM\Entity(repositoryClass="Desymfony\DesymfonyBundle\Entity\PonenteRepository")
 */
class Ponente
{
    /**
    * @ORM\Id
    * @ORM\Column(type="integer")
    * @ORM\GeneratedValue(strategy="IDENTITY")
    */
    protected $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $nombre;

    /**
     * @ORM\Column(type="string")
     */
    protected $apellidos;

    /**
     * @ORM\Column(type="text")
     */
    protected $biografia;

    /**
     * @ORM\Column(type="string")
     */
    protected $telefono;

    /**
     * @ORM\Column(type="string")
     */
    protected $url;

    /**
     * @ORM\Column(type="string")
     */
    protected $email;

    /**
     * @ORM\Column(type="string")
     */
    protected $twitter;

    /**
     * @ORM\Column(type="string")
     */
    protected $linkedin;

    /**
     * @ORM\OneToMany(targetEntity="Ponencia", mappedBy="ponente")
     */
    private $ponencias;

    public function __construct()
    {
      $this->ponencias = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function __toString()
    {
        return $this->getNombreCompleto();
    }

    public function getNombreCompleto()
    {
        return $this->getNombre().' '.$this->getApellidos();
    }


    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    }

    /**
     * Get nombre
     *
     * @return string $nombre
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set apellidos
     *
     * @param string $apellidos
     */
    public function setApellidos($apellidos)
    {
        $this->apellidos = $apellidos;
    }

    /**
     * Get apellidos
     *
     * @return string $apellidos
     */
    public function getApellidos()
    {
        return $this->apellidos;
    }

    /**
     * Set biografia
     *
     * @param text $biografia
     */
    public function setBiografia($biografia)
    {
        $this->biografia = $biografia;
    }

    /**
     * Get biografia
     *
     * @return text $biografia
     */
    public function getBiografia()
    {
        return $this->biografia;
    }

    /**
     * Set telefono
     *
     * @param string $telefono
     */
    public function setTelefono($telefono)
    {
        $this->telefono = $telefono;
    }

    /**
     * Get telefono
     *
     * @return string $telefono
     */
    public function getTelefono()
    {
        return $this->telefono;
    }

    /**
     * Set url
     *
     * @param string $url
     */
    public function setUrl($url)
    {
        $this->url = $url;
    }

    /**
     * Get url
     *
     * @return string $url
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set email
     *
     * @param string $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * Get email
     *
     * @return string $email
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set twitter
     *
     * @param string $twitter
     */
    public function setTwitter($twitter)
    {
        $this->twitter = $twitter;
    }

    /**
     * Get twitter
     *
     * @return string $twitter
     */
    public function getTwitter()
    {
        return $this->twitter;
    }

    /**
     * Set linkedin
     *
     * @param string $linkedin
     */
    public function setLinkedin($linkedin)
    {
        $this->linkedin = $linkedin;
    }

    /**
     * Get linkedin
     *
     * @return string $linkedin
     */
    public function getLinkedin()
    {
        return $this->linkedin;
    }

    /**
     * Add ponencias
     *
     * @param Desymfony\DesymfonyBundle\Entity\Ponencia $ponencias
     */
    public function addPonencias(\Desymfony\DesymfonyBundle\Entity\Ponencia $ponencias)
    {
        $this->ponencias[] = $ponencias;
    }

    /**
     * Get ponencias
     *
     * @return Doctrine\Common\Collections\Collection $ponencias
     */
    public function getPonencias()
    {
        return $this->ponencias;
    }
}

src/Desymfony/DesymfonyBundle/Entity/Usuario.php
<?php

namespace Desymfony\DesymfonyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
//use Symfony\Component\Validator\Mapping\ClassMetadata;

use Desymfony\DesymfonyBundle\Validator\DNI;

/**
 * Desymfony\DesymfonyBundle\Entity
 *
 * @ORM\Table(name="usuario")
 * @ORM\Entity()
 * @UniqueEntity(fields="email")
 */
class Usuario implements UserInterface, \Serializable
{
    /*
     * Implementation of UserInterface
     */

    public function getRoles()
    {
        return array('ROLE_USER');
    }

    public function getSalt()
    {
        return false;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {

    }

    public function equals(UserInterface $user)
    {
        return $user->getUsername() == $this->getUsername();
    }

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
    * @ORM\Column(type="string")
    * @Assert\NotBlank()
    * @Assert\MinLength(3)
    * @Assert\MaxLength(20)
    */
    protected $nombre;

    /**
    * @ORM\Column(type="string")
    * @Assert\NotBlank()
    * @Assert\MinLength(3)
    * @Assert\MaxLength(20)
    */
    protected $apellidos;

    /**
    * @ORM\Column(type="string")
    * @Assert\NotBlank()
    * @DNI()
    */
    protected $dni;

    /**
    * @ORM\Column(type="string")
    * @Assert\NotBlank()
    * @Assert\MinLength(5)
    * @Assert\MaxLength(100)
    */
    protected $direccion;

    /**
    * @ORM\Column(type="string")
    * @Assert\NotBlank()
    */
    protected $telefono;

    /**
    * @ORM\Column(type="string")
    * @Assert\NotBlank()
    * @Assert\Email()
    */
    protected $email;

    /**
    * @ORM\Column(type="string")
    * @Assert\NotBlank()
    * @Assert\MinLength(5)
    * @Assert\MaxLength(10)
    */
    protected $password;

    /**
    * @ORM\ManyToMany(targetEntity="Ponencia", mappedBy="usuarios")
    */
    protected $ponencias;

    public function __construct()
    {
        $this->ponencias = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    public function __toString()
    {
        return $this->getNombreCompleto();
    }

    public function getNombreCompleto()
    {
        return $this->getNombre().' '.$this->getApellidos();
    }

    public function serialize()
    {
        return serialize(array(
            $this->getEmail()
        ));
    }

    public function unserialize($serialized)
    {
        $arr = unserialize($serialized);
        $this->setEmail($arr[0]);
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    }

    /**
     * Get nombre
     *
     * @return string $nombre
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set apellidos
     *
     * @param string $apellidos
     */
    public function setApellidos($apellidos)
    {
        $this->apellidos = $apellidos;
    }

    /**
     * Get apellidos
     *
     * @return string $apellidos
     */
    public function getApellidos()
    {
        return $this->apellidos;
    }

    /**
     * Set dni
     *
     * @param string $dni
     */
    public function setDni($dni)
    {
        $this->dni = $dni;
    }

    /**
     * Get dni
     *
     * @return string $dni
     */
    public function getDni()
    {
        return $this->dni;
    }

    /**
     * Set direccion
     *
     * @param string $direccion
     */
    public function setDireccion($direccion)
    {
        $this->direccion = $direccion;
    }

    /**
     * Get direccion
     *
     * @return string $direccion
     */
    public function getDireccion()
    {
        return $this->direccion;
    }

    /**
     * Set telefono
     *
     * @param string $telefono
     */
    public function setTelefono($telefono)
    {
        $this->telefono = $telefono;
    }

    /**
     * Get telefono
     *
     * @return string $telefono
     */
    public function getTelefono()
    {
        return $this->telefono;
    }

    /**
     * Set email
     *
     * @param string $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * Get email
     *
     * @return string $email
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }

    /**
     * Get password
     *
     * @return string $password
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Add ponencias
     *
     * @param Desymfony\DesymfonyBundle\Entity\Ponencia $ponencias
     */
    public function addPonencias(\Desymfony\DesymfonyBundle\Entity\Ponencia $ponencias)
    {
        if (!$this->hasPonencia($ponencias)) {
            $this->ponencias[] = $ponencias;
            return true;
        }

        return false;
    }

    public function hasPonencia(\Desymfony\DesymfonyBundle\Entity\Ponencia $ponencia)
    {
        foreach ($this->ponencias as $value) {
            if ($value->getId() == $ponencia->getId()) {
                return true;
            }
        }

        return false;
    }

    /**
     * Get ponencias
     *
     * @return Doctrine\Common\Collections\Collection $ponencias
     */
    public function getPonencias()
    {
        return $this->ponencias;
    }

    /**
     * Get numero de ponencias
     *
     * @return integer $numeroPonencias
     */
    public function getNumeroPonencias()
    {
        return count($this->ponencias);
    }

    /*
     * Dejo comentado este código para que se viera como se haría mediante código PHP
     * Creo que en ocasiones puede ser preferible esta manera por tener todas las
     * validaciones a un sólo vistazo

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        // Validación global
        $metadata->addConstraint(new UniqueEntity(array('fields' => 'email')));

        // Nombre
        $metadata->addPropertyConstraint('nombre',    new Assert\NotBlank()   );
        $metadata->addPropertyConstraint('nombre',    new Assert\MinLength(3) );
        $metadata->addPropertyConstraint('nombre',    new Assert\MaxLength(20));

        // Apellidos
        $metadata->addPropertyConstraint('apellidos', new Assert\NotBlank()   );
        $metadata->addPropertyConstraint('apellidos', new Assert\MinLength(3) );
        $metadata->addPropertyConstraint('apellidos', new Assert\MaxLength(20));

        // DNI
        $metadata->addPropertyConstraint('dni'      , new Assert\NotBlank()   );
        $metadata->addPropertyConstraint('dni'      , new DNI() );

        // Dirección
        $metadata->addPropertyConstraint('direccion', new Assert\NotBlank()   );
        $metadata->addPropertyConstraint('direccion', new Assert\MinLength(5) );
        $metadata->addPropertyConstraint('direccion', new Assert\MaxLength(100));

        // Telefóno
        $metadata->addPropertyConstraint('telefono' , new Assert\NotBlank());

        // Contraseña
        $metadata->addPropertyConstraint('password',  new Assert\NotBlank());
        $metadata->addPropertyConstraint('password',  new Assert\MinLength(5) );
        $metadata->addPropertyConstraint('password',  new Assert\MaxLength(10));

        // Email
        $metadata->addPropertyConstraint('email'   ,  new Assert\NotBlank());
        $metadata->addPropertyConstraint('email'   ,  new Assert\Email() );


        $metadata->addPropertyConstraint('password',  new Assert\NotBlank());
    }
     *
     */
}

src/Desymfony/DesymfonyBundle/Resources/views/layout.html.twig
{% extends "::base.html.twig" %}

{% block header %}
  <h1 class="grid_6"><a href="{{ path('portada') }}">Jornadas Symfony 2011</a></h1>

  <nav class="grid_10">
  <ul>
    <li><a href="{{ path('ponencias') }}">Ponencias</a></li>
    <li><a href="{{ path('ponentes') }}">Ponentes</a></li>

    {% if is_granted('ROLE_ADMIN') %}
    <li><a href="{{ path('admin_portada') }}">Admin</a></li>
    {% else %}
    <li><a href="{{ app.user ? path('perfil') : path('registro') }}">
      {{ app.user ? 'Mi perfil' : 'Regístrate' }}
    </a></li>
    {% endif %}

    <li><a href="{{ path('estatica', { 'pagina': 'contacto'}) }}">Contacto</a></li>

    {% if app.user %}
    <li><a href="{{ path('logout') }}">Salir</a></li>
    {% endif %}
  </ul>
  </nav>
{% endblock %}

{% block body %}
  <article id="contenido">
    <section id="principal" class="grid_12">
      {% block contenido %}{% endblock %}
    </section>
    <section id="lateral" class="grid_4">
      {% block lateral %}
          <div class="usuario">
          {% if is_granted(['ROLE_USER']) %}
          {# usuario #}
              <h4><a href="{{ path('perfil') }}">{{ app.user.nombreCompleto }}</a></h4>
              <p>Estás apuntado a <strong>{{ app.user.numeroPonencias }}</strong> ponencias</p>
          {% elseif is_granted(['ROLE_ADMIN']) %}
          {# administrador #}
              <h4>Administrador</h4>
              <p>Estás logueado como <strong>{{ app.user.username }}</strong></p>
          {% else %}
          {# no ha hecho login #}
              <a href="{{ path('registro') }}" class="btn">Regístrate</a>
              <p>¿Ya estás registrado? <a href="{{ path('login') }}">Haz login</a></p>
          {% endif %}
          </div>

          <p>Las Jornadas Symfony 2011 se celebran del <strong>1 al 3 de julio</strong> de 2011 en la Universidad Jaume I de  Castellón</p>
          <p>El aforo está limitado a las 175 primeras inscripciones recibidas</p>

          <h3>Ventajas de asistir</h3>
          <ul>
              <li>1 curso de 6 horas sobre Symfony2</li>
              <li>10 sesiones prácticas</li>
              <li>Varios talleres prácticos</li>
              <li>Mesas redondas</li>
              <li>Networking</li>
          </ul>
      {% endblock %}
    </section>
  </article>
{% endblock %}

src/Desymfony/DesymfonyBundle/Resources/views/layout_admin.html.twig
{% extends "::base.html.twig" %}

{% block header %}
<h1 class="grid_6 alpha"><a href="{{ path('admin_portada') }}">Gestión de deSymfony.com</a></h1>

<nav class="grid_10 omega">
    <ul>
        <li><a href="{{ path('admin_ponencia_list') }}">Ponencias</a></li>
        <li><a href="{{ path('portada') }}">Sitio público</a></li>
        <li>{{ app.user.username }} <a href="{{ path('logout') }}">salir</a></li>
    </ul>
</nav>

<h1>{{ block('title') }}</h1>
{% endblock %}

src/Desymfony/DesymfonyBundle/Resources/views/layout_movil.html.twig
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Jornadas de Symfony{% endblock %} | Desymfony.com</title>
	<link rel="stylesheet"  href="http://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.min.css" />
	<script src="http://code.jquery.com/jquery-1.6.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.min.js"></script>

</head>
<body>
<div data-role="page" id="{% block pageid '' %}" class="type-{% block pagetype 'interior' %}">
{% block header %}
{% endblock %}

{% block contenido %}
{% endblock %}

{% block footer %}
<div  data-role="footer" class="ui-bar" data-theme="b">
    <a href="{{ path('m_estatica', { 'pagina': 'copyright'}) }}">&copy; {{ 'now' | date('Y') }} - desymfony</a>
    <a href="{{ path('m_estatica', { 'pagina': 'privacidad'}) }}"> Privacidad</a>
    <a href="{{ path('m_estatica', { 'pagina': 'condiciones'}) }}"> Condiciones de uso</a>
</div>
{% endblock %}

</div>
</body>
</html>